### ISSUE TITLE
Error on make

### ISSUE THREAD

**Issue by Arieg419** [fedorn/lemur-4.11#1]
Hey,

First off, thank you for posting this :)

I am getting an error when running make. I attached a screenshot.

Can you help me in figuring out why it doesn't recognize the type name?

I see you clearly defined it in lines 44 and 45. 

Thank you,
Omer
<img width="950" alt="screen shot 2016-11-29 at 1 00 12 am" src="https://cloud.githubusercontent.com/assets/8246234/20689653/390de804-b5cf-11e6-8d99-9cc35f14700c.png">

**Comment by fedorn** [comment]
Hi. You're welcome.
What is your OS, gcc, libc++ version?
Did you follow instructions from INSTALL file?
Have you tried homebrew formula from here https://github.com/fedorn/homebrew-ir?
Unfortunately, I don't have a MacBook anymore, but I'll try to help as much as I can.

**Comment by Arieg419** [comment]
Hey,

I am running OS X version 10.11.16. g++ is 4.2.1. 

I was trying to use 4.12, and apply your fixes from 4.11 - so pretty sure that was what was breaking it.

I cloned your repo now, and seems to work :)

Also, what is the purpose of the homebrew-ir formula? Is it different than simply cloning your repo?

Thank you for the quick response!

**Comment by fedorn** [comment]
I'm glad you were able to fix it.
Homebrew formula is useful if you're using homebrew to manage your software http://brew.sh/

**Comment by Arieg419** [comment]
Thanks friend, best of luck!
